sudo: required
language: java

services:
  - docker

env:
  global:
  - secure: oJyLvxIpWo737FfGJVwcXkd9f9/wGSrWj8K1wqce1w+9Ma+ueVaeBeOLsPJ1jVvluGRjGRcfCGyGaXKFGhFpNPPnTtAjuvYLHK7CJNMc535Is3yBi+dhbpY3JIursv8lYrXqoWIeQIA/sbVG8B3yXXxPgz4b5pZ2RBsAucZ6Cd4Dn1cyxL1A/xA1NkyHG8Q/1FiL3jTlGQQrlZXxZLTn+ytQqHk0nBXJXmw1E+k8UlnAP/YsZ1IiIG7IP3gf1KnVfxUpa6f01iR0uTYbSsUQsIM1qO4r9yDCQlKeBALEnutX99oBjjjCDeIXaLEE9J/1H0zFsqRPXvXs41MdSQ2WWVf3MqQtxkpCCp0ZHVWC7JAMhIYSM/mvySSsKJQFKVkKlkarc1+zDjGo4Csf1P17fNQYmjCXrUAC2OeZU5zGckFXNh24AVXCyn2oEefOJGxXqv9V7V4LOX53FyFQULRe1p902u2EhHayAAMBnqBS4oE8JrArvmcO2/wHPm6bku8fb5uB0I3X+j7Ow9+Qd3Kvp7sOAyTZS1OhEiVeF+tayToXk0t7ND56cC8WuXO3Hd5zLLxoum/VFuFytXoJmYtb4VubWXh5uewM0atEbDZ9eeKU2AUVDVLOoTyZXP/W6g1hIFaWiWzl+3gitLHcVxuPgzrzcLLmGuGrHOOaCMV5aPU=
  - secure: MpVEp2/wCaX+2Ui3H8lApQLnaAqn2+LsanhIUe1BAvhfkUdrB1up/+3BoahLnFT1XTeCIGs30rT6zUscgerHCSV3DrDn6gsND/YbjslrkRzFMG628Gj6eCEhbpv47da1A30faHMQLx9ALo4hRw8k1RyR9KkjS2RTKC7MT2wYVC+7BJSPMmeWzwaH2pPg4l4HYrtuHSFPfqRdRvJA8GkAy78MfVWekWooeDLN3dI4a3NBJL5m+tNgqOFXL0qGrfJCcr4fcrzLwLKfBf7FN+R1/pOI8YFD1FB07ER2lsbv2RYdLd5ge3WDvzweMQlbM8Nr6MdC5wQR3Dgz/oVBsCuFiU/jcZxNQWY96F562HrE0ORgnJjbjfeP1YUIp6Hoi3RLXuuve7zCTKsBKKH+O+Pc3wLEDLXSQLVE1g3TAPzH8OjNm0ZmC8PbiTGYG5fcs5sneJ420kVRbJexXh4FJ7NhiSX80MsEMT8ftqDaYajH0lNCB4BJR1ji+Pb40ku1j5p/zEQShhbVRQNVx5dlaVXe6qzjf2Cg32edi+tkDZzUfpn1/h9fwju/cKD/6e8Ly0xHXXiexSZSrdv6q3ViMFRe0o/fnxneK7MhMvkA3yUnwc0kXsaoLBRJ6ZOYlLsdQNFFmgiapDvaVE5hCGGOvAlnfZFYJXK5G/+NztTEAsIE8b4=

script:
  - mvn clean install -B

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build -t acebook-millieandco .
- docker tag acebook-millieandco williampowell/acebook-millieandco:1.0-SNAPSHOT
- docker push williampowell/acebook-millieandco:1.0-SNAPSHOT

deploy:
  provider: heroku
  api_key:
    secure: Iyhh8f4KyZOwYUIvXGNVPSZ9SqvgnyaxDTP4Kwvo1uQMYaRkRcl0mrTl9FrwceA4DaWZ9bE5RhIfL0FpLmVXhI5Oz6jelnKWGKQyIMP20Ny6o49LTUG+qWBqQmSL1oUzjgYITfOxF8Esddv/mTUdZ/v/wCBQGzWArAQ+3F5N1rWpgjJDXvbdPalw6J96/bRkqh/46edFpmAhdGNQAhFXtbyGnu/P8hCZoECTdOSbE2Zl5LjGm4hy6KKLQojjNAf3ZPX2C1aolK8nA/MaSZweBcmroRksmabaQJSfL+ygwkFCeDoHn3kUmV7hTzJdEyJzzjUAtezi1Dvd8CMR6GKcP4bSycyUjevHxe/jzT1LFpKncczamLQmWFHLGv5Ol9a3oxF8hpbKhyBdAzH6s1HX/qGPdq2Nk+QMpmEQxqE86l3rhVMl/WaRmnrTx8err3yiMZaFtm7yGj93Nc8DimzL1PksyIkZUaT6oglrCYBm6yqUzU5D/xib0VGMKU+HaACat0rNzO1D7sxbEsqvidYjBPtMwXijDB3Hk+dt9xDGuwKAvn1v3eakKtcde9gueatlQEpYpIvVGfNWmhV8ieiLqWgRXbeC+j65la8ZiIkPxb3blEf9pvzo6zIP7nqfd0XJholj7B4/G4vTk4S35kOoaRmbU+Pqkx597Tse0GzRJao=
  app: acebook-millieandco
